### ISSUE TITLE
PinePhone Pro support

### ISSUE THREAD

**Issue by CCF100** [JasonG-FR/PineBattery#5]
It would be nice if PineBattery supported the PinePhone Pro!

**Comment by JasonG-FR** [comment]
I'll gladly add support for the PinePhone Pro, but I don't own one yet so if you have one, can you send me back the output of this command:

`ls /sys/class/power_supply/`

Thanks.

**Comment by CCF100** [comment]
> I'll gladly add support for the PinePhone Pro, but I don't own one yet so if you have one, can you send me back the output of this command:
> 
> `ls /sys/class/power_supply/`
> 
> Thanks.

Sure, here you go:
```
❯ ls -lah /sys/class/power_supply
total 0
drwxr-xr-x  2 root root 0 Jan 18  2013 .
drwxr-xr-x 63 root root 0 Jan 18  2013 ..
lrwxrwxrwx  1 root root 0 Jan 18  2013 battery -> ../../devices/platform/ff3c0000.i2c/i2c-0/0-001c/rk818-battery/power_supply/battery
lrwxrwxrwx  1 root root 0 Jan 18  2013 rk818-charger -> ../../devices/platform/ff3c0000.i2c/i2c-0/0-001c/rk818-charger/power_supply/rk818-charger
lrwxrwxrwx  1 root root 0 Jan 18  2013 rk818-usb -> ../../devices/platform/ff3c0000.i2c/i2c-0/0-001c/rk818-charger/power_supply/rk818-usb
lrwxrwxrwx  1 root root 0 Jan 18  2013 tcpm-source-psy-4-0022 -> ../../devices/platform/ff3d0000.i2c/i2c-4/4-0022/power_supply/tcpm-source-psy-4-0022
```

**Comment by CCF100** [comment]
> 
some more ls:
```
❯ ls -lah /sys/class/power_supply/battery/
total 0
drwxr-xr-x 5 root root    0 Feb  2 20:06 .
drwxr-xr-x 3 root root    0 Feb  2 20:06 ..
-r--r--r-- 1 root root 4.0K Feb  2 20:06 capacity
-r--r--r-- 1 root root 4.0K Feb  2 20:06 charge_counter
-r--r--r-- 1 root root 4.0K Feb  2 20:06 charge_full
-r--r--r-- 1 root root 4.0K Feb  2 21:31 current_max
-r--r--r-- 1 root root 4.0K Feb  2 20:06 current_now
lrwxrwxrwx 1 root root    0 Feb  2 21:31 device -> ../../../rk818-battery
-r--r--r-- 1 root root 4.0K Feb  2 21:31 health
drwxr-xr-x 3 root root    0 Feb  2 20:06 hwmon1
drwxr-xr-x 2 root root    0 Feb  2 21:31 power
-r--r--r-- 1 root root 4.0K Feb  2 20:06 present
-r--r--r-- 1 root root 4.0K Feb  2 20:06 status
lrwxrwxrwx 1 root root    0 Feb  2 20:06 subsystem -> ../../../../../../../../class/power_supply
-r--r--r-- 1 root root 4.0K Feb  2 20:06 temp
-r--r--r-- 1 root root 4.0K Feb  2 20:06 type
-rw-r--r-- 1 root root 4.0K Feb  2 20:06 uevent
-r--r--r-- 1 root root 4.0K Feb  2 21:31 voltage_max
-r--r--r-- 1 root root 4.0K Feb  2 20:06 voltage_now
drwxr-xr-x 2 root root    0 Feb  2 20:06 wakeup2
```

**Comment by CCF100** [comment]
I created a PR: #6

**Comment by JasonG-FR** [comment]
Thanks, I merged it to a new branch (devel).

- 6271b21f2132174d5504f5ea0f231cb2949fb7be : I added the detection to hopefully fix the issues on the PPP. I'll try it on my PinePhone later to see if it didn't break anything. It also works on my PineBookPro as a side effect.
- fd2ed908cdf807211b1de92d35075af2e3252a11 : I also added the detection for the sensors, I'll have to test it on the OG PinePhone as well.
- b59aafa017da427f75450827854d1d3641c9a600 : I stopped the health check from being updated every 500ms.

**Comment by JasonG-FR** [comment]
Works fine on the OG PinePhone except for sensors not being ordered correctly.

Tell me if it works on the PPP and I'll merge it.

Edit: dd44bb38a270783c3b2a36f862eb0c5588c40cd2 : sensors are now alphabetically sorted.

**Comment by CCF100** [comment]
> Works fine on the OG PinePhone except for sensors not being ordered correctly.
> 
> Tell me if it works on the PPP and I'll merge it.
> 
> Edit: [dd44bb3](https://github.com/JasonG-FR/PineBattery/commit/dd44bb38a270783c3b2a36f862eb0c5588c40cd2) : sensors are now alphabetically sorted.

Just tried it on my PinePhone Pro, can confirm it works!
